name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  set-up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

  deploy:
    runs-on: ubuntu-latest
    needs: set-up

    steps:
      - name: Hola mundo
        run: echo "${{ secrets.NAME}}"
