name: Prueba simple de PHP

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2
      - name: Ver version de PHP
        run: php -v

      - name: Iniciar servidor PHP
        run: |
          php -S localhost:8000 > /dev/null 2>&1 & 
          sleep 3
          curl http://localhost:8000
