name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  set-up:
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "hola mundo"

  deploy:
    if: false
    needs: set-up
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: echo "test"
